function marketingdata = importfile(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   MARKETINGDATA = IMPORTFILE(FILENAME) Reads data from text file FILENAME
%   for the default selection.
%
%   MARKETINGDATA = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from
%   rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   marketingdata = importfile('marketingdata.csv', 2, 2241);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2021/11/09 21:20:27

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Read columns of data as strings:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric strings to numbers.
% Replace non-numeric strings with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = dataArray{col};
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[1,2,5,6,7,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27]
    % Converts strings in the input cell array to numbers. Replaced non-numeric
    % strings with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1);
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData{row}, regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if any(numbers==',');
                thousandsRegExp = '^\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(numbers, thousandsRegExp, 'once'));
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric strings to numbers.
            if ~invalidThousandsSeparator;
                numbers = textscan(strrep(numbers, ',', ''), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch me
        end
    end
end

% Convert the contents of columns with dates to MATLAB datetimes using date
% format string.
try
    dates{8} = datetime(dataArray{8}, 'Format', 'MM/dd/yyyy', 'InputFormat', 'MM/dd/yyyy');
catch
    try
        % Handle dates surrounded by quotes
        dataArray{8} = cellfun(@(x) x(2:end-1), dataArray{8}, 'UniformOutput', false);
        dates{8} = datetime(dataArray{8}, 'Format', 'MM/dd/yyyy', 'InputFormat', 'MM/dd/yyyy');
    catch
        dates{8} = repmat(datetime([NaN NaN NaN]), size(dataArray{8}));
    end
end

anyBlankDates = cellfun(@isempty, dataArray{8});
anyInvalidDates = isnan(dates{8}.Hour) - anyBlankDates;
dates = dates(:,8);

%% Split data into numeric and cell columns.
rawNumericColumns = raw(:, [1,2,5,6,7,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27]);
rawCellColumns = raw(:, [3,4,28]);


%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),rawNumericColumns); % Find non-numeric cells
rawNumericColumns(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
marketingdata = table;
marketingdata.ID = cell2mat(rawNumericColumns(:, 1));
marketingdata.Year_Birth = cell2mat(rawNumericColumns(:, 2));
marketingdata.Education = rawCellColumns(:, 1);
marketingdata.Marital_Status = rawCellColumns(:, 2);
marketingdata.Income = cell2mat(rawNumericColumns(:, 3));
marketingdata.Kidhome = cell2mat(rawNumericColumns(:, 4));
marketingdata.Teenhome = cell2mat(rawNumericColumns(:, 5));
marketingdata.Dt_Customer = dates{:, 1};
marketingdata.Recency = cell2mat(rawNumericColumns(:, 6));
marketingdata.MntWines = cell2mat(rawNumericColumns(:, 7));
marketingdata.MntFruits = cell2mat(rawNumericColumns(:, 8));
marketingdata.MntMeatProducts = cell2mat(rawNumericColumns(:, 9));
marketingdata.MntFishProducts = cell2mat(rawNumericColumns(:, 10));
marketingdata.MntSweetProducts = cell2mat(rawNumericColumns(:, 11));
marketingdata.MntGoldProds = cell2mat(rawNumericColumns(:, 12));
marketingdata.NumDealsPurchases = cell2mat(rawNumericColumns(:, 13));
marketingdata.NumWebPurchases = cell2mat(rawNumericColumns(:, 14));
marketingdata.NumCatalogPurchases = cell2mat(rawNumericColumns(:, 15));
marketingdata.NumStorePurchases = cell2mat(rawNumericColumns(:, 16));
marketingdata.NumWebVisitsMonth = cell2mat(rawNumericColumns(:, 17));
marketingdata.AcceptedCmp3 = cell2mat(rawNumericColumns(:, 18));
marketingdata.AcceptedCmp4 = cell2mat(rawNumericColumns(:, 19));
marketingdata.AcceptedCmp5 = cell2mat(rawNumericColumns(:, 20));
marketingdata.AcceptedCmp1 = cell2mat(rawNumericColumns(:, 21));
marketingdata.AcceptedCmp2 = cell2mat(rawNumericColumns(:, 22));
marketingdata.Response = cell2mat(rawNumericColumns(:, 23));
marketingdata.Complain = cell2mat(rawNumericColumns(:, 24));
marketingdata.Country = rawCellColumns(:, 3);

% For code requiring serial dates (datenum) instead of datetime, uncomment
% the following line(s) below to return the imported dates as datenum(s).

% marketingdata.Dt_Customer=datenum(marketingdata.Dt_Customer);

